-- DHANYA Enterprise Schema for H2 Database
CREATE TABLE IF NOT EXISTS MILL_PROFILES (
    MILL_CODE VARCHAR(50) PRIMARY KEY,
    MILL_NAME VARCHAR(150) NOT NULL,
    MANAGER_NAME VARCHAR(100) NOT NULL,
    USERNAME VARCHAR(50) UNIQUE NOT NULL,
    PASSWORD_HASH VARCHAR(100) NOT NULL,
    DISTRICT VARCHAR(50) NOT NULL,
    ALLOCATED_QUOTA_MT INT NOT NULL,
    STATUS VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS DHANYA_CMR_RECORDS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TRUCK_NO VARCHAR(50) NOT NULL,
    PASS_NO VARCHAR(50) NOT NULL,
    MILL_CODE VARCHAR(50) NOT NULL,
    FARMER_NAME VARCHAR(100) NOT NULL,
    FARMER_AADHAAR VARCHAR(20) NOT NULL,
    PADDY_VARIETY VARCHAR(50) NOT NULL,
    GOVT_GROSS_KG DOUBLE NOT NULL,
    GOVT_TARE_KG DOUBLE NOT NULL,
    GOVT_NET_KG DOUBLE NOT NULL,
    MILL_GROSS_KG DOUBLE NOT NULL,
    MILL_TARE_KG DOUBLE NOT NULL,
    MILL_NET_KG DOUBLE NOT NULL,
    MOISTURE_PERCENT DOUBLE NOT NULL,
    NET_VARIANCE_KG DOUBLE NOT NULL,
    STATUS VARCHAR(30) NOT NULL,
    RECONCILIATION_FLAG VARCHAR(20) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS FARMER_ACCOUNTS (
    FARMER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    FARMER_NAME VARCHAR(100) NOT NULL,
    AADHAAR_NO VARCHAR(20) NOT NULL,
    PHONE_NO VARCHAR(20) NOT NULL,
    BANK_ACCOUNT VARCHAR(50) NOT NULL,
    IFSC_CODE VARCHAR(20) NOT NULL,
    VILLAGE VARCHAR(100) NOT NULL,
    PADDY_SOLD_QTL DOUBLE NOT NULL,
    DBT_PAYABLE_AMOUNT DOUBLE NOT NULL,
    DBT_STATUS VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS AUDIT_LOGS (
    LOG_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ACTION_NAME VARCHAR(100) NOT NULL,
    PERFORMED_BY VARCHAR(100) NOT NULL,
    DETAILS TEXT NOT NULL,
    IP_ADDRESS VARCHAR(50),
    TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
